import { create } from "zustand";
import { persist } from "zustand/middleware";
import type { BookingStep } from "@/features/bookings/types";

export type CompletedBooking = {
  id: string;
  artistSlug: string;
  artistName: string;
  artistAvatar: string;
  serviceId: string;
  serviceName: string;
  date: string;
  timeSlot: string;
  price: number;
  status: "Upcoming" | "Completed" | "Cancelled";
};

export type BookingNotification = {
  id: string;
  title: string;
  message: string;
  category: "booking" | "system" | "promo" | "ai";
  isRead: boolean;
  time: string;
  bookingId?: string;
};

type BookingState = {
  // Wizard flow state
  step: BookingStep;
  artistSlug: string | null;
  serviceId: string | null;
  date: string | null;
  timeSlot: string | null;

  // Completed bookings
  bookings: CompletedBooking[];

  // Notifications generated by the app
  notifications: BookingNotification[];

  setStep: (step: BookingStep) => void;
  setArtistSlug: (slug: string) => void;
  setServiceId: (id: string | null) => void;
  setDate: (date: string | null) => void;
  setTimeSlot: (time: string | null) => void;
  resetBooking: () => void;
  addBooking: (booking: CompletedBooking) => void;
  cancelBooking: (id: string) => void;
  markNotificationRead: (id: string) => void;
  markAllNotificationsRead: () => void;
};

export const useBookingStore = create<BookingState>()(
  persist(
    (set) => ({
      step: 1,
      artistSlug: null,
      serviceId: null,
      date: null,
      timeSlot: null,
      bookings: [],
      notifications: [],

      setStep: (step) => set({ step }),
      setArtistSlug: (artistSlug) => set({ artistSlug }),
      setServiceId: (serviceId) => set({ serviceId }),
      setDate: (date) => set({ date }),
      setTimeSlot: (timeSlot) => set({ timeSlot }),

      // Only resets the wizard flow, not the completed bookings or notifications
      resetBooking: () =>
        set({ step: 1, artistSlug: null, serviceId: null, date: null, timeSlot: null }),

      addBooking: (booking) =>
        set((state) => {
          const now = new Date();
          const timeStr = now.toLocaleTimeString("en-IN", { hour: "2-digit", minute: "2-digit" });
          const notification: BookingNotification = {
            id: `notif-${booking.id}`,
            title: "Booking Confirmed! 🎉",
            message: `Your appointment with ${booking.artistName} for ${booking.serviceName} has been confirmed. See you on ${new Date(booking.date).toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "numeric" })} at ${booking.timeSlot}.`,
            category: "booking",
            isRead: false,
            time: `Just now · ${timeStr}`,
            bookingId: booking.id,
          };
          return {
            bookings: [...state.bookings, booking],
            notifications: [notification, ...state.notifications],
          };
        }),

      cancelBooking: (id) =>
        set((state) => {
          const booking = state.bookings.find((b) => b.id === id);
          const notification: BookingNotification = booking
            ? {
                id: `notif-cancel-${id}`,
                title: "Booking Cancelled",
                message: `Your appointment with ${booking.artistName} for ${booking.serviceName} has been cancelled.`,
                category: "booking",
                isRead: false,
                time: "Just now",
                bookingId: id,
              }
            : null as unknown as BookingNotification;

          return {
            bookings: state.bookings.map((b) =>
              b.id === id ? { ...b, status: "Cancelled" } : b
            ),
            notifications: booking
              ? [notification, ...state.notifications]
              : state.notifications,
          };
        }),

      markNotificationRead: (id) =>
        set((state) => ({
          notifications: state.notifications.map((n) =>
            n.id === id ? { ...n, isRead: true } : n
          ),
        })),

      markAllNotificationsRead: () =>
        set((state) => ({
          notifications: state.notifications.map((n) => ({ ...n, isRead: true })),
        })),
    }),
    {
      name: "beautibridge-bookings",
      partialize: (state) => ({
        bookings: state.bookings,
        notifications: state.notifications,
        // Persist wizard state so refreshing mid-flow doesn't lose data
        artistSlug: state.artistSlug,
        serviceId: state.serviceId,
        date: state.date,
        timeSlot: state.timeSlot,
        step: state.step,
      }),
    }
  )
);
