import type { Artist } from "./types";

export const MOCK_ARTISTS: Artist[] = [
  {
    id: "1",
    slug: "ananya-r",
    name: "Ananya R.",
    avatar: "/images/marketing/bridal-look.svg",
    coverImage: "/images/marketing/bridal-look.svg",
    category: "bridal",
    services: ["Bridal Makeup", "Engagement Look", "Reception Glam"],
    city: "Visakhapatnam",
    state: "Andhra Pradesh",
    rating: 4.9,
    reviewCount: 312,
    startingPrice: 2800,
    bio: "Specialist in bridal and occasion makeup with over 8 years of experience transforming brides on their special day. Expert in airbrush and HD makeup techniques.",
    yearsExperience: 8,
    isVerified: true,
    badge: "Top Rated",
    portfolio: [
      "/images/marketing/bridal-look.svg",
      "/images/marketing/hero-makeup.svg",
      "/images/marketing/nail-art.svg",
    ],
    languages: ["Telugu", "English", "Hindi"],
    availability: "available",
  },
  {
    id: "2",
    slug: "priya-m",
    name: "Priya M.",
    avatar: "/images/marketing/hair-style.svg",
    coverImage: "/images/marketing/hair-style.svg",
    category: "hair",
    services: ["Hair Styling", "Bridal Updo", "Smoothening", "Keratin"],
    city: "Coimbatore",
    state: "Tamil Nadu",
    rating: 4.8,
    reviewCount: 187,
    startingPrice: 1500,
    bio: "Creative hair artist blending modern trends with classic styles. Trained in Paris and specialising in bridal updos and editorial hair looks.",
    yearsExperience: 6,
    isVerified: true,
    badge: "Rising Star",
    portfolio: [
      "/images/marketing/hair-style.svg",
      "/images/marketing/bridal-look.svg",
    ],
    languages: ["Tamil", "English"],
    availability: "available",
  },
  {
    id: "3",
    slug: "nisha-k",
    name: "Nisha K.",
    avatar: "/images/marketing/nail-art.svg",
    coverImage: "/images/marketing/nail-art.svg",
    category: "nail",
    services: ["Gel Nails", "Nail Art", "Nail Extensions", "Spa Manicure"],
    city: "Nagpur",
    state: "Maharashtra",
    rating: 4.7,
    reviewCount: 243,
    startingPrice: 900,
    bio: "Certified nail technician with a flair for intricate nail art. Specialising in 3D designs, gel art, and seasonal themes that tell a story.",
    yearsExperience: 5,
    isVerified: true,
    badge: "Highly Booked",
    portfolio: [
      "/images/marketing/nail-art.svg",
      "/images/marketing/hero-makeup.svg",
    ],
    languages: ["Marathi", "Hindi", "English"],
    availability: "busy",
  },
  {
    id: "4",
    slug: "kavya-s",
    name: "Kavya S.",
    avatar: "/images/marketing/hero-makeup.svg",
    coverImage: "/images/marketing/hero-makeup.svg",
    category: "makeup",
    services: ["Party Makeup", "Smoky Eye", "Natural Glam", "Contouring"],
    city: "Bangalore",
    state: "Karnataka",
    rating: 4.9,
    reviewCount: 421,
    startingPrice: 1800,
    bio: "Makeup artist with 10 years in the industry, known for flawless skin prep and editorial-quality looks. Worked with leading fashion magazines and celebrity clients.",
    yearsExperience: 10,
    isVerified: true,
    badge: "Top Rated",
    portfolio: [
      "/images/marketing/hero-makeup.svg",
      "/images/marketing/bridal-look.svg",
      "/images/marketing/nail-art.svg",
    ],
    languages: ["Kannada", "English", "Hindi"],
    availability: "available",
  },
  {
    id: "5",
    slug: "meera-t",
    name: "Meera T.",
    avatar: "/images/marketing/bridal-look.svg",
    coverImage: "/images/marketing/hair-style.svg",
    category: "skincare",
    services: ["Facial", "Glow Treatment", "Acne Care", "Anti-Ageing"],
    city: "Chennai",
    state: "Tamil Nadu",
    rating: 4.8,
    reviewCount: 156,
    startingPrice: 1200,
    bio: "Licensed aesthetician specialising in skin health and glow treatments. Combine science-backed techniques with natural ingredients for lasting results.",
    yearsExperience: 7,
    isVerified: true,
    portfolio: ["/images/marketing/hero-makeup.svg"],
    languages: ["Tamil", "English"],
    availability: "available",
  },
  {
    id: "6",
    slug: "riya-d",
    name: "Riya D.",
    avatar: "/images/marketing/nail-art.svg",
    coverImage: "/images/marketing/hero-makeup.svg",
    category: "editorial",
    services: [
      "Editorial Makeup",
      "Fantasy Looks",
      "SFX",
      "Avant-Garde Styling",
    ],
    city: "Mumbai",
    state: "Maharashtra",
    rating: 4.9,
    reviewCount: 89,
    startingPrice: 4500,
    bio: "Creative director and makeup artist pushing the boundaries of beauty. Work has appeared in Vogue India, Harper's Bazaar, and major fashion weeks.",
    yearsExperience: 9,
    isVerified: true,
    badge: "Top Rated",
    portfolio: [
      "/images/marketing/hero-makeup.svg",
      "/images/marketing/bridal-look.svg",
      "/images/marketing/hair-style.svg",
    ],
    languages: ["Hindi", "English", "Marathi"],
    availability: "available",
  },
  {
    id: "7",
    slug: "divya-n",
    name: "Divya N.",
    avatar: "/images/marketing/hair-style.svg",
    coverImage: "/images/marketing/bridal-look.svg",
    category: "bridal",
    services: [
      "South Indian Bridal",
      "Saree Draping",
      "Floral Jewellery Styling",
    ],
    city: "Hyderabad",
    state: "Telangana",
    rating: 4.7,
    reviewCount: 204,
    startingPrice: 3200,
    bio: "Expert in traditional South Indian bridal looks with expertise in authentic temple jewellery styling, floral work, and classic saree draping techniques.",
    yearsExperience: 8,
    isVerified: true,
    badge: "Highly Booked",
    portfolio: [
      "/images/marketing/bridal-look.svg",
      "/images/marketing/hair-style.svg",
    ],
    languages: ["Telugu", "Tamil", "Hindi", "English"],
    availability: "available",
  },
  {
    id: "8",
    slug: "sneha-g",
    name: "Sneha G.",
    avatar: "/images/marketing/hero-makeup.svg",
    coverImage: "/images/marketing/nail-art.svg",
    category: "nail",
    services: ["Ombre Nails", "Chrome Nails", "Nail Wraps", "Paraffin Wax"],
    city: "Pune",
    state: "Maharashtra",
    rating: 4.6,
    reviewCount: 178,
    startingPrice: 750,
    bio: "Trendsetting nail artist bringing global nail trends to your fingertips. Specialises in chrome, holographic, and seasonal nail art designs.",
    yearsExperience: 4,
    isVerified: true,
    badge: "Rising Star",
    portfolio: [
      "/images/marketing/nail-art.svg",
      "/images/marketing/hero-makeup.svg",
    ],
    languages: ["Marathi", "Hindi", "English"],
    availability: "available",
  },
  {
    id: "9",
    slug: "aisha-r",
    name: "Aisha R.",
    avatar: "/images/marketing/bridal-look.svg",
    coverImage: "/images/marketing/hair-style.svg",
    category: "hair",
    services: ["Hair Coloring", "Balayage", "Highlights", "Hair Spa"],
    city: "Delhi",
    state: "Delhi",
    rating: 4.8,
    reviewCount: 267,
    startingPrice: 2000,
    bio: "Colour specialist and hair stylist trained in Italy. Creating custom colour formulas that flatter every skin tone with zero damage techniques.",
    yearsExperience: 11,
    isVerified: true,
    badge: "Top Rated",
    portfolio: [
      "/images/marketing/hair-style.svg",
      "/images/marketing/bridal-look.svg",
      "/images/marketing/hero-makeup.svg",
    ],
    languages: ["Hindi", "Urdu", "English"],
    availability: "available",
  },
  {
    id: "10",
    slug: "pooja-l",
    name: "Pooja L.",
    avatar: "/images/marketing/nail-art.svg",
    coverImage: "/images/marketing/hero-makeup.svg",
    category: "makeup",
    services: ["HD Makeup", "Airbrush", "Mature Skin Makeup", "GRWM Sessions"],
    city: "Jaipur",
    state: "Rajasthan",
    rating: 4.7,
    reviewCount: 134,
    startingPrice: 1600,
    bio: "Certified HD and airbrush makeup specialist. Known for lightweight yet long-lasting looks perfect for the Rajasthan climate and vibrant wedding culture.",
    yearsExperience: 6,
    isVerified: true,
    portfolio: [
      "/images/marketing/hero-makeup.svg",
      "/images/marketing/bridal-look.svg",
    ],
    languages: ["Rajasthani", "Hindi", "English"],
    availability: "busy",
  },
  {
    id: "11",
    slug: "trisha-v",
    name: "Trisha V.",
    avatar: "/images/marketing/bridal-look.svg",
    coverImage: "/images/marketing/hero-makeup.svg",
    category: "skincare",
    services: [
      "Korean Skincare Routine",
      "Hydra Facial",
      "LED Therapy",
      "Dermaplaning",
    ],
    city: "Bangalore",
    state: "Karnataka",
    rating: 4.9,
    reviewCount: 302,
    startingPrice: 2200,
    bio: "K-beauty enthusiast and licensed skincare therapist bringing the best of Korean skincare to India. Treatments tailored to Indian skin tones and concerns.",
    yearsExperience: 5,
    isVerified: true,
    badge: "Rising Star",
    portfolio: ["/images/marketing/hero-makeup.svg"],
    languages: ["Kannada", "English"],
    availability: "available",
  },
  {
    id: "12",
    slug: "zara-k",
    name: "Zara K.",
    avatar: "/images/marketing/hair-style.svg",
    coverImage: "/images/marketing/bridal-look.svg",
    category: "editorial",
    services: ["Runway Makeup", "Photoshoot Styling", "Concept Looks"],
    city: "Mumbai",
    state: "Maharashtra",
    rating: 4.8,
    reviewCount: 72,
    startingPrice: 5500,
    bio: "High fashion makeup artist who has worked backstage at Lakme Fashion Week and FDCI India Fashion Week. Transforming concepts into wearable art.",
    yearsExperience: 7,
    isVerified: true,
    portfolio: [
      "/images/marketing/hero-makeup.svg",
      "/images/marketing/hair-style.svg",
    ],
    languages: ["Hindi", "English"],
    availability: "available",
  },
  {
    id: "13",
    slug: "anjali-p",
    name: "Anjali P.",
    avatar: "/images/marketing/hero-makeup.svg",
    coverImage: "/images/marketing/nail-art.svg",
    category: "bridal",
    services: [
      "Punjabi Bridal",
      "Phulkari Styling",
      "Pre-Bridal Package",
      "Mehendi Look",
    ],
    city: "Delhi",
    state: "Delhi",
    rating: 4.8,
    reviewCount: 289,
    startingPrice: 3500,
    bio: "Specialist in Punjabi and North Indian bridal looks. Renowned for bold, vivid makeup paired with stunning dupatta styling and traditional jewellery draping.",
    yearsExperience: 9,
    isVerified: true,
    badge: "Highly Booked",
    portfolio: [
      "/images/marketing/bridal-look.svg",
      "/images/marketing/hero-makeup.svg",
      "/images/marketing/hair-style.svg",
    ],
    languages: ["Hindi", "Punjabi", "English"],
    availability: "available",
  },
  {
    id: "14",
    slug: "sana-m",
    name: "Sana M.",
    avatar: "/images/marketing/nail-art.svg",
    coverImage: "/images/marketing/hair-style.svg",
    category: "hair",
    services: ["Scalp Treatment", "Deep Conditioning", "Protein Treatment"],
    city: "Kolkata",
    state: "West Bengal",
    rating: 4.6,
    reviewCount: 119,
    startingPrice: 1100,
    bio: "Trichologist and hair care specialist focused on scalp health and hair restoration. Blends Ayurvedic wisdom with modern science for transformative results.",
    yearsExperience: 5,
    isVerified: false,
    portfolio: ["/images/marketing/hair-style.svg"],
    languages: ["Bengali", "Hindi", "English"],
    availability: "available",
  },
  {
    id: "15",
    slug: "lata-s",
    name: "Lata S.",
    avatar: "/images/marketing/bridal-look.svg",
    coverImage: "/images/marketing/hero-makeup.svg",
    category: "makeup",
    services: [
      "Natural Makeup",
      "No-Makeup Makeup",
      "Teen & Young Adult Looks",
    ],
    city: "Surat",
    state: "Gujarat",
    rating: 4.5,
    reviewCount: 98,
    startingPrice: 800,
    bio: "Advocate for enhancing natural beauty without heavy coverage. Specialised in clean beauty and skin-forward looks that let your true radiance shine through.",
    yearsExperience: 3,
    isVerified: true,
    badge: "Rising Star",
    portfolio: ["/images/marketing/hero-makeup.svg"],
    languages: ["Gujarati", "Hindi", "English"],
    availability: "available",
  },
  {
    id: "16",
    slug: "rekha-b",
    name: "Rekha B.",
    avatar: "/images/marketing/nail-art.svg",
    coverImage: "/images/marketing/bridal-look.svg",
    category: "nail",
    services: ["Acrylic Nails", "Nail Repair", "Builder Gel", "Nail Art"],
    city: "Mumbai",
    state: "Maharashtra",
    rating: 4.7,
    reviewCount: 211,
    startingPrice: 1100,
    bio: "10 years in the nail industry with expertise in structural nail enhancements and intricate nail art. Running a home studio in Bandra, Mumbai.",
    yearsExperience: 10,
    isVerified: true,
    portfolio: [
      "/images/marketing/nail-art.svg",
      "/images/marketing/hero-makeup.svg",
    ],
    languages: ["Hindi", "Marathi", "English"],
    availability: "available",
  },
  {
    id: "17",
    slug: "meghna-c",
    name: "Meghna C.",
    avatar: "/images/marketing/hero-makeup.svg",
    coverImage: "/images/marketing/hair-style.svg",
    category: "skincare",
    services: ["Medi-Facial", "Vitamin C Treatment", "Brightening Peel"],
    city: "Hyderabad",
    state: "Telangana",
    rating: 4.7,
    reviewCount: 143,
    startingPrice: 1800,
    bio: "Clinical skin therapist providing results-driven treatments in a hygienic, professional environment. Partner with dermatologists for complex skin concerns.",
    yearsExperience: 6,
    isVerified: true,
    portfolio: ["/images/marketing/hero-makeup.svg"],
    languages: ["Telugu", "Hindi", "English"],
    availability: "busy",
  },
  {
    id: "18",
    slug: "shweta-j",
    name: "Shweta J.",
    avatar: "/images/marketing/hair-style.svg",
    coverImage: "/images/marketing/nail-art.svg",
    category: "hair",
    services: ["Blowout", "Hair Setting", "Braiding", "Wedding Hair"],
    city: "Pune",
    state: "Maharashtra",
    rating: 4.6,
    reviewCount: 155,
    startingPrice: 900,
    bio: "Hair stylist specialising in elegant updos and romantic bridal braids. Trained at L'Oréal Academy and winner of the Maharashtra State Hairstyling Award.",
    yearsExperience: 7,
    isVerified: true,
    portfolio: [
      "/images/marketing/hair-style.svg",
      "/images/marketing/bridal-look.svg",
    ],
    languages: ["Marathi", "Hindi", "English"],
    availability: "available",
  },
  {
    id: "19",
    slug: "farida-h",
    name: "Farida H.",
    avatar: "/images/marketing/bridal-look.svg",
    coverImage: "/images/marketing/hero-makeup.svg",
    category: "bridal",
    services: ["Muslim Bridal", "Nikah Look", "Sehband Styling"],
    city: "Kolkata",
    state: "West Bengal",
    rating: 4.8,
    reviewCount: 176,
    startingPrice: 2600,
    bio: "Specialist in Muslim bridal traditions and contemporary fusion looks. Known for achieving elegance with a modern twist for Nikah and reception ceremonies.",
    yearsExperience: 8,
    isVerified: true,
    portfolio: [
      "/images/marketing/bridal-look.svg",
      "/images/marketing/hair-style.svg",
    ],
    languages: ["Urdu", "Bengali", "Hindi", "English"],
    availability: "available",
  },
  {
    id: "20",
    slug: "deepika-a",
    name: "Deepika A.",
    avatar: "/images/marketing/nail-art.svg",
    coverImage: "/images/marketing/hero-makeup.svg",
    category: "editorial",
    services: ["Bridal Editorial", "Magazine Shoots", "Concept Makeup"],
    city: "Bangalore",
    state: "Karnataka",
    rating: 4.7,
    reviewCount: 63,
    startingPrice: 3800,
    bio: "Award-winning editorial makeup artist bridging the gap between high fashion and accessible beauty. Collaborated with top photographers across South India.",
    yearsExperience: 6,
    isVerified: true,
    portfolio: [
      "/images/marketing/hero-makeup.svg",
      "/images/marketing/bridal-look.svg",
    ],
    languages: ["Kannada", "English"],
    availability: "available",
  },
  {
    id: "21",
    slug: "sunita-r",
    name: "Sunita R.",
    avatar: "/images/marketing/hero-makeup.svg",
    coverImage: "/images/marketing/bridal-look.svg",
    category: "makeup",
    services: [
      "Mehendi Makeup",
      "Sangeet Look",
      "Function Makeup",
      "Saree Makeup",
    ],
    city: "Jaipur",
    state: "Rajasthan",
    rating: 4.6,
    reviewCount: 219,
    startingPrice: 1400,
    bio: "Celebrating Indian wedding traditions with full-function makeup packages. Skilled in making clients look their best from mehendi to reception.",
    yearsExperience: 7,
    isVerified: true,
    badge: "Highly Booked",
    portfolio: [
      "/images/marketing/bridal-look.svg",
      "/images/marketing/hero-makeup.svg",
    ],
    languages: ["Rajasthani", "Hindi", "English"],
    availability: "available",
  },
  {
    id: "22",
    slug: "maya-v",
    name: "Maya V.",
    avatar: "/images/marketing/hair-style.svg",
    coverImage: "/images/marketing/nail-art.svg",
    category: "nail",
    services: ["Japanese Nail Art", "Kawaii Nails", "Minimalist Nail Design"],
    city: "Bangalore",
    state: "Karnataka",
    rating: 4.9,
    reviewCount: 94,
    startingPrice: 1300,
    bio: "Nail artist with training in Tokyo bringing Japanese nail art culture to Bangalore. Specialises in delicate, intricate designs with premium gel products.",
    yearsExperience: 4,
    isVerified: true,
    badge: "Rising Star",
    portfolio: ["/images/marketing/nail-art.svg"],
    languages: ["Kannada", "English", "Japanese"],
    availability: "available",
  },
  {
    id: "23",
    slug: "ishita-p",
    name: "Ishita P.",
    avatar: "/images/marketing/bridal-look.svg",
    coverImage: "/images/marketing/hair-style.svg",
    category: "skincare",
    services: ["Skin Brightening", "Chemical Peel", "Oxygen Facial"],
    city: "Chennai",
    state: "Tamil Nadu",
    rating: 4.6,
    reviewCount: 128,
    startingPrice: 1500,
    bio: "Skin rejuvenation specialist with a focus on chemical exfoliation and brightening protocols. Offers personalised skin plans with monthly follow-ups.",
    yearsExperience: 6,
    isVerified: true,
    portfolio: ["/images/marketing/hero-makeup.svg"],
    languages: ["Tamil", "English"],
    availability: "available",
  },
  {
    id: "24",
    slug: "radhika-s",
    name: "Radhika S.",
    avatar: "/images/marketing/nail-art.svg",
    coverImage: "/images/marketing/hero-makeup.svg",
    category: "hair",
    services: ["Digital Perm", "Rebonding", "Hair Extensions", "Hair Botox"],
    city: "Mumbai",
    state: "Maharashtra",
    rating: 4.8,
    reviewCount: 347,
    startingPrice: 2500,
    bio: "Master hair transformation specialist with certifications from Wella and Schwarzkopf. Known for dramatic hair makeovers and celebrity hair transformations.",
    yearsExperience: 12,
    isVerified: true,
    badge: "Top Rated",
    portfolio: [
      "/images/marketing/hair-style.svg",
      "/images/marketing/bridal-look.svg",
      "/images/marketing/hero-makeup.svg",
    ],
    languages: ["Hindi", "Marathi", "English"],
    availability: "available",
  },
];
